apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: app
        - name: SERVICE_TAGS
          value: dev
        image: laravel
        imagePullPolicy: ""
        name: app
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/www
          name: app-claim0
        - mountPath: /usr/local/etc/php/conf.d/local.ini
          name: app-claim1
        workingDir: /var/www
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
      - name: app-claim1
        persistentVolumeClaim:
          claimName: app-claim1
status: {}
